version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: project-mosaic-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/project-mosaic
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret
    depends_on:
      - mongodb
      - redis
    command: npm run dev
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: project-mosaic-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=project-mosaic
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: project-mosaic-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: project-mosaic-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander
    container_name: project-mosaic-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
